### ISSUE TITLE
NaN when the observation point is on an edge extension

### ISSUE THREAD

**Issue by Alxndrdl** [krcools/WiltonInts84.jl#1]
The following code reproduces the problem :

using WiltonInts84
using FixedSizeArrays
v1p = Vec(4.12, 1.74, 1.8);
v2p = Vec(2.04, 3.47, -3.5);
v3p = Vec(-4.21, 3.2, 0.08);
lvp = v2p-v1p; # an edge vector
observationPointp = v1p + 2.84*lvp;
I, J = wiltonints(v1p,v2p,v3p,observationPointp,Val{0})

Output :

I, J = wiltonints(v1p,v2p,v3p,observationPointp,Val{0})
([0.0,NaN,21.2019],3-elementArray{FixedSizeArrays.Vec{3,Float64},1}:
 Vec(NaN,NaN,NaN)
 Vec(NaN,NaN,NaN)
 Vec(51.6734,-81.6246,269.519)
)

**Comment by krcools** [comment]
Like you told me the singularity lies on the extension of on of the sides...

![image](https://cloud.githubusercontent.com/assets/10086147/19526217/a9eff25c-961b-11e6-8d55-cd012f891895.png)

Looking into it...

**Comment by krcools** [comment]
This is caused by testing certain parameters exactly for zero-ness. I replaced this with a relaxed condition exact up to `eps(T)*1_000`.

**Comment by krcools** [comment]
Fixed and passed all the tests on my machine. Let's see about the CI in a minute. This issue is now part of the test suite.

**Comment by Alxndrdl** [comment]
The problem is still there if the observation point is almost on the extension of the edge : 

v1 = Vec(4.12, 1.74, 1.8);
v2 = Vec(2.04, 3.47, -3.5);
v3 = Vec(-4.21, 3.2, 0.08);
tn = cross(v1-v2, v1-v3);
tn = tn / norm(tn); # triangle normal
lv = v2-v1; # an edge vector
observationPoint = v1 + 2.84 \* lv+0.0000001 \* tn;
I, J = wiltonints(v1,v2,v3,observationPoint,Val{0})

Output :

((8.809057927550157e-10,NaN,21.20194037423228),(Vec(NaN,NaN,NaN),Vec(NaN,NaN,NaN),Vec(51.673369080078686,-81.62464351541101,269.5190660372406)),(Vec(NaN,NaN,NaN),Vec(NaN,NaN,NaN),Vec(103.34673768391737,-163.249291087962,539.0381309370712)))
